### ISSUE TITLE
SECURITY: ex_doc 

### ISSUE THREAD

**Issue by Muelsy** [avitex/elixir-rcon#6]
Hi,

I'm a bug bounty specialist. I've identified a CRITICAL security defect in your code. Currently ex_doc is at version 0.22.0. The CURRENT version is 0.22.1.

Please, I beg of you, fix this defect, your users are suffering.

Please send bug bounties to bugBountySpecialist@c0refailure.com

Thanks,
James Dyson

**Comment by avitex** [comment]
Hi Muelsy,

Thank you for your bug report. I'm currently blocked on an internal milestone in my life before I can pull in the required changes to fixed this bug.

I'm aware this is at great detriment to my users, but it's a risk I have had to sign off on.

Thanks
